name: tutorial
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - scikit-learn==0.23.2
      - mlflow>=1.0
      - pandas
      - pymysql
      - boto3
      - tensorflow
      - protobuf==3.20.*
